export const COLORS = {
  teal800: '#085041',
  teal600: '#0F6E56',
  teal400: '#1D9E75',
  teal50:  '#E1F5EE',
  amber800: '#633806',
  amber400: '#BA7517',
  amber50:  '#FAEEDA',
  purple800: '#3C3489',
  purple400: '#7F77DD',
  purple50:  '#EEEDFE',
  gray800: '#2C2C2A',
  gray400: '#888780',
  gray100: '#D3D1C7',
  gray50:  '#F1EFE8',
}

export const NAV_CONFIG = {
  insider: [
    { id: 'feed',    icon: '◈', label: 'Feed'    },
    { id: 'matches', icon: '⟳', label: 'Matches' },
    { id: 'profile', icon: '○', label: 'Profile' },
  ],
  seeker: [
    { id: 'companies', icon: '⊙', label: 'Companies' },
    { id: 'matches',   icon: '⟳', label: 'Matches'   },
    { id: 'profile',   icon: '○', label: 'Profile'   },
  ],
}

export const BADGES = {
  communityVerified: { label: 'Community Verified',     color: 'teal'   },
  halalFriendly:     { label: 'Halal-Friendly WS',      color: 'amber'  },
  topReferrer:       { label: 'Top Referrer',           color: 'purple' },
  noVisa:            { label: 'No visa required',       color: 'gray'   },
  visaRequired:      { label: 'Visa: H1B needed',       color: 'amber'  },
}

export const TALENT = [
  {
    initials: 'ZA',
    name: 'Z. Ahmed',
    role: 'Senior Backend Engineer',
    impact: '5 yrs at AWS · Distributed systems · Led team of 8',
    color: 'teal',
    badges: ['communityVerified', 'halalFriendly'],
    location: 'NYC',
    relocate: true,
    visa: false,
  },
  {
    initials: 'FH',
    name: 'F. Hassan',
    role: 'Staff ML Engineer',
    impact: '7 yrs industry · OpenAI alum · Published researcher',
    color: 'amber',
    badges: ['communityVerified'],
    location: 'SF',
    relocate: false,
    visa: false,
  },
  {
    initials: 'SK',
    name: 'S. Khan',
    role: 'Product Manager · Growth',
    impact: 'Grew MAU 3× at Series B · Ex-Meta PM · NYC → Open to relocate',
    color: 'purple',
    badges: ['communityVerified', 'noVisa'],
    location: 'NYC',
    relocate: true,
    visa: false,
  },
  {
    initials: 'NA',
    name: 'N. Ali',
    role: 'Data Engineer · Analytics',
    impact: '4 yrs fintech · dbt + Spark expert · Remote only · Visa required',
    color: 'gray',
    badges: ['communityVerified', 'visaRequired'],
    location: 'Remote',
    relocate: false,
    visa: true,
  },
]

export const COMPANIES = [
  {
    initials: 'G',
    name: 'Google',
    departments: 'Engineering · Design · Marketing',
    insiders: 3,
    color: 'blue',
    badges: ['halalFriendly'],
    extra: 'Prayer rooms',
  },
  {
    initials: 'SF',
    name: 'Salesforce',
    departments: 'Sales · Engineering',
    insiders: 2,
    color: 'teal',
    badges: [],
    extra: 'ERG: Muslim Network',
  },
  {
    initials: 'A',
    name: 'Amazon',
    departments: 'Engineering · Operations · PM',
    insiders: 7,
    color: 'orange',
    badges: ['halalFriendly'],
    extra: '',
  },
  {
    initials: 'S',
    name: 'Stripe',
    departments: 'Engineering · Product',
    insiders: 1,
    color: 'green',
    badges: ['communityVerified'],
    extra: '',
  },
  {
    initials: 'AI',
    name: 'Anthropic',
    departments: 'Research · Engineering · Policy',
    insiders: 2,
    color: 'purple',
    badges: ['communityVerified', 'halalFriendly'],
    extra: '',
  },
]